[colors]
background              = #DD0f0f0f
background-alt          = 
foreground              = #DDffffff
foreground-alt          = 

; Red
candy-apple-red         = #FF0800
turkey-red              = #A91101

; Yellow
mindaro                 = #E3F988 
chartreuse              = #DFFF00
amber                   = #FFBF00

; Green 
cyan                    = #00FFFF
bright-green            = #66FF00
apple-green             = #8DB600
pigment-green           = #00A550
jade                    = #00A86B
sea-green               = #2E8B57
office-green            = #008000
british-racing-green    = #004225

; Blue
ice-blue                = #99FFFF
aero                    = #00B9E8
azul                    = #0070BB
polynesian-blue         = #224C98

; Violet
electric-indigo         = #6F00FF
ultra-violet            = #645394
rebecca-purple          = #663399

; White
anti-flash-white        = #F2F3F4
viory                   = #FFFFF0
white-smoke             = #F5F5F5
mint-cream              = #F5FFFA
nyanza                  = #E9FFDB

; Gray
platinum                = #E5E4E2
ash-gray                = #B2BEB5
cadet-gray              = #91A3B0
battleship-gray         = #848482

; Black
eerie-black             = #1B1B1B
rich-black              = #010B13

; Orange
tangelo                 = #F94D00

; Brown
russet                  = #80461B