[module/date]
    type = internal/date
    interval = 1
    date = %a, %b %d
    time = %k:%M
    label = %{T3}%date%%{T-}  %time%

[module/xworkspaces]
    type = internal/xworkspaces
    enable-click = true
    enable-scroll = false
    format-padding = 1
    format = <label-state>
    label-monitor = %name%
    icon-default = "A"

    background = #22FFFFFF
    foreground = #FFFFFF

    border-size = 10
    border-top-left-radius = 10
    border-top-right-radius = 10
    border-bottom-left-radius = 10
    border-bottom-right-radius = 10

    label-active = %name%
    label-active-background = #307E39
    label-active-foreground = #DCF2DF
    ; label-active-underline= ${colors.}
    label-active-padding = 1

    label-occupied = %name%
    label-occupied-background = #368F41
    label-occupied-foreground = #A8DEAE
    ; label-occupied-underline= ${colors.}
    label-occupied-padding = 1

    label-urgent = %name%
    label-urgent-background = #368F41
    label-urgent-foreground = #A8DEAE
    ; label-urgent-underline= ${colors.}
    label-urgent-padding = 1

    label-empty = %name%
    label-empty-background = #368F41
    label-empty-foreground = #A8DEAE
    ; label-empty-underline= ${colors.}
    label-empty-padding = 1


[module/xwindow]
    type = internal/xwindow
    format = <label>
    label = %title:0:32:...%
    label-empty = " "