[module/date]
    type = internal/date
    interval = 1
    date = %a, %b %d
    time = %k:%M
    label = %{T3}%date%%{T-}  %time%

[module/xworkspaces]
    type = internal/xworkspaces
    enable-click = true
    enable-scroll = false
    format-padding = 1
    format = <label-state>
    label-monitor = %name%
    icon-default = "A"

    label-active = %name%
    label-active-background = ${colors.background}
    label-active-foreground = ${colors.foreground}
    ; label-active-underline= ${colors.}
    label-active-padding = 1

    label-occupied = %name%
    label-occupied-background = ${colors.background}
    label-occupied-foreground = ${colors.foreground}
    ; label-occupied-underline= ${colors.}
    label-occupied-padding = 1

    label-urgent = %name%
    label-urgent-background = ${colors.background}
    label-urgent-foreground = ${colors.foreground}
    ; label-urgent-underline= ${colors.}
    label-urgent-padding = 1

    label-empty = %name%
    label-empty-background = ${colors.background}
    label-empty-foreground = ${colors.foreground}
    ; label-empty-underline= ${colors.}
    label-empty-padding = 1

[module/xwindow]
    type = internal/xwindow
    format = <label>
    label = %title:0:32:...%
    label-empty = " "